#!/bin/bash
# update docs with pydoc

pydoc host > docs/hosts.pydoc
pydoc services > docs/services.pydoc

for file in services/[^_]*.py; do
    path=${file/.py/}
    obj=${path/\//.}
    pydoc $obj > docs/services.${obj/*./}.pydoc
done
