#!/bin/bash
# update docs with pydoc

cd ..

pydoc netstatus.host > netstatus/docs/host.pydoc
pydoc netstatus.services > netstatus/docs/services.pydoc

for file in netstatus/services/[^_]*.py; do
    path=${file/.py/}
    obj=${path/\//.}
    obj=${obj/\//.}
    pydoc $obj > netstatus/docs/services.${obj/*./}.pydoc
done
